stages:
  - build

build:
  stage: build
  tags:
    - docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
