stages:
  - init
  - ss
  - tex
  - llvm-gcc
  - llvm-clang
  - misc
  - dl

init:
  stage: init
  tags:
    - docker
  only:
    - /^build-init$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE:stage-init -f stage/init .
    - docker push $CI_REGISTRY_IMAGE:stage-init

ss:
  stage: ss
  tags:
    - docker
  only:
    - /^build-(init|ss)$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE:stage-ss -f stage/ss .
    - docker push $CI_REGISTRY_IMAGE:stage-ss

tex:
  stage: tex
  tags:
    - docker
  only:
    - /^build-(init|ss|tex)$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE:stage-tex -f stage/tex .
    - docker push $CI_REGISTRY_IMAGE:stage-tex

llvm-gcc:
  stage: llvm-gcc
  tags:
    - docker
  only:
    - /^build-(init|ss|tex|llvm-gcc)$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE:stage-llvm-gcc -f stage/llvm-gcc .
    - docker push $CI_REGISTRY_IMAGE:stage-llvm-gcc

llvm-clang:
  stage: llvm-clang
  tags:
    - docker
  only:
    - /^build-(init|ss|tex|llvm-gcc|llvm-clang)$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE:stage-llvm-clang -f stage/llvm-clang .
    - docker push $CI_REGISTRY_IMAGE:stage-llvm-clang

misc:
  stage: misc
  tags:
    - docker
  only:
    - /^build-(init|ss|tex|llvm-gcc|llvm-clang|misc)$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE:stage-misc -f stage/misc .
    - docker push $CI_REGISTRY_IMAGE:stage-misc

dl:
  stage: dl
  tags:
    - docker
  only:
    - /^build-.*$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --pull --no-cache --cpu-shares 128 -t $CI_REGISTRY_IMAGE -f stage/dl .
    - docker push $CI_REGISTRY_IMAGE
