stages:
  - init
  - repo
  - font
  - pkg-skip
  - ss
  - tex
  - llvm-gcc
  - llvm-clang
  - misc
  - dl
  - edit
  - finish

init:
  stage: init
  tags:
    - docker
    - gpu
  only:
    - /^build-init$/
  except:
    - branches
  script:
    - until docker pull centos/systemd; do echo "Retry docker pull..."; done
    - gitlab-ci/build_stage.sh

repo:
  stage: repo
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

font:
  stage: font
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

pkg-skip:
  stage: pkg-skip
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

ss:
  stage: ss
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

tex:
  stage: tex
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss|tex)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

llvm-gcc:
  stage: llvm-gcc
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss|tex|llvm-gcc)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

llvm-clang:
  stage: llvm-clang
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss|tex|llvm-gcc|llvm-clang)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

misc:
  stage: misc
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss|tex|llvm-gcc|llvm-clang|misc)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

dl:
  stage: dl
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss|tex|llvm-gcc|llvm-clang|misc|dl)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

edit:
  stage: edit
  tags:
    - docker
    - gpu
  only:
    - /^build-(init|repo|font|pkg-skip|pkg-all|ss|tex|llvm-gcc|llvm-clang|misc|dl|edit)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

finish:
  stage: finish
  tags:
    - docker
    - gpu
  only:
    - /^build-.*$/
  except:
    - branches
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#   - docker tag $CI_REGISTRY_IMAGE:stage-edit $CI_REGISTRY_IMAGE:latest
    - time docker-squash -v $CI_REGISTRY_IMAGE -t latest
    - time docker push $CI_REGISTRY_IMAGE:latest
