stages:
  - init
  - repo
  - font
  - pkg-skip
  - tex
  - ss
  - infra
  - llvm
  - util
  - misc
  - dl
  - edit
  - finish

init:
  stage: init
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-init$/
  except:
    - branches
  script:
    - until docker pull centos; do echo "Retry docker pull..."; done
    - gitlab-ci/build_stage.sh

repo:
  stage: repo
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

font:
  stage: font
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

pkg-skip:
  stage: pkg-skip
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-skip)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

tex:
  stage: tex
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|tex)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

ss:
  stage: ss
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|tex|ss)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

infra:
  stage: infra
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|ss|tex|infra)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

llvm:
  stage: llvm
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|ss|tex|infra|llvm)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

util:
  stage: util
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|ss|tex|infra|llvm|util)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

misc:
  stage: misc
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|ss|tex|infra|llvm|util|misc)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

dl:
  stage: dl
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|ss|tex|infra|llvm|util|misc|dl)$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh
    - docker tag $CI_REGISTRY_IMAGE:stage-dl $CI_REGISTRY_IMAGE:stage-edit

.edit:
  stage: edit
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-edit$/
  except:
    - branches
  script:
    - gitlab-ci/build_stage.sh

finish:
  stage: finish
  retry: 2
  tags:
    - docker
    - gpu
  only:
    - /^(build|resume)-(init|repo|font|pkg-(skip|all)|ss|tex|infra|llvm|util|misc|dl|edit|finish)$/
  except:
    - branches
  script:
    - docker login --password-stdin --username $CI_REGISTRY_USER $CI_REGISTRY <<< "$CI_REGISTRY_PASSWORD"
    - docker tag $CI_REGISTRY_IMAGE:stage-edit $CI_REGISTRY_IMAGE:latest
    - time docker push $CI_REGISTRY_IMAGE:latest

